[package]
name = "clio-auth"
description = "OAuth 2 helper library for CLI and desktop applications"
authors = ["Eric McIntyre <mac@riversoforion.com>"]
license = "MIT"
version = "0.8.1"
edition = "2021"
repository = "https://github.com/riversoforion/clio-auth"
documentation = "https://docs.rs/clio-auth"
keywords = ["auth", "oauth2", "cli", "desktop"]
categories = ["authentication", "command-line-interface"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
log = "0.4.29"
oauth2 = "4.4.2"
open = "5.3.3"
serde = "1.0.228"
tokio = { version = "1.50.0", features = ["full"] }
poem = { version = "3.1.12" }
url = "2.5.8"
thiserror = "1.0.69"

[dev-dependencies]
rstest = "0.26.1"
mockall = "0.14.0"
anyhow = "1.0.102"
pretty_env_logger = "0.5.0"
reqwest = { version = "0.12.28", features = ["default", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[[example]]
name = "auth0"

[[example]]
name = "youtube"
