[package]
name = "clio-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
oauth2 = "4.2"
tokio = "1"
reqwest = { version = "0.11", features = ["default", "json"] }
hyper = { version = "0.14", features = ["full"] }
crossbeam = "0.8"
open = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
rstest = "0.17"
mockall = "0.11.3"
