[package]
name = "clio-auth"
description = "OAuth 2 helper library for CLI and desktop applications"
authors = ["Eric McIntyre <mac@riversoforion.com>"]
license = "MIT"
version = "1.0.2"
edition = "2021"
repository = "https://github.com/riversoforion/clio-auth"
documentation = "https://docs.rs/clio-auth"
keywords = ["auth", "oauth2", "cli", "desktop"]
categories = ["authentication", "command-line-interface"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
constant_time_eq = "0.5.0"
html-escape = "0.2.15"
log = "0.4.33"
oauth2 = "5.0.0"
open = "5.4.1"
poem = "3.1.12"
serde = "1.0.229"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = [
  "rt-multi-thread",
  "sync",
  "time",
  "macros",
  "signal",
] }
url = "2.5.8"

[dev-dependencies]
pretty_env_logger = "0.5.0"
reqwest = { version = "0.13.4", features = ["json"] }
rstest = "0.26.1"
serde = { version = "1.0.229", features = ["derive"] }

[[example]]
name = "auth0"

[[example]]
name = "youtube"
