name: Publish Release

on:
  release:
    types: ["published"]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always
  TRIGGER: ${{ (github.event_name == 'release') && 'release' || 'pull_request' }}

jobs:
  sanity-check:
    # Anything we publish should've already run tests on multiple platforms, but just double-check
    name: Sanity check code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  publish:
    name: Publish crate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publishing dry run
        if: env.TRIGGER == 'pull_request'
        run: echo "::notice title=Publish Result::Pull request detected! Crate will not be published."


      # Push release to crates.io
      - name: Publish to crates.io
        if: env.TRIGGER == 'release'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --dry-run
